# Generated by Django 5.2.10 on 2026-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection, sent to student', null=True),
        ),
    ]
