# Generated by Django 5.2.10 on 2026-01-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_admin_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='core_admina_timesta_168ff2_idx',
            old_name='core_admin_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='core_admina_admin_u_fc7dd3_idx',
            old_name='core_admin_user_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='core_admina_action_2db477_idx',
            old_name='core_admin_action_idx',
        ),
        migrations.RenameIndex(
            model_name='adminactivitylog',
            new_name='core_admina_model_n_187242_idx',
            old_name='core_admin_model_idx',
        ),
        migrations.RenameIndex(
            model_name='systemmetric',
            new_name='core_system_metric__540133_idx',
            old_name='core_system_metric_idx_1',
        ),
        migrations.RenameIndex(
            model_name='systemmetric',
            new_name='core_system_timesta_dd0b60_idx',
            old_name='core_system_timestamp_idx',
        ),
    ]
