# Generated by Django 5.2.10 on 2026-03-12 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(choices=[('research_proposal', 'Research Proposal and Dissertation Writing'), ('project_proposal', 'Project Proposal'), ('research_consultancy', 'Research Consultancy'), ('project_management', 'Project Management'), ('coaching', 'Coaching'), ('business_plan', 'Business Plan Creation'), ('spss_training', 'SPSS Training'), ('stata_training', 'STATA Training'), ('r_training', 'R Training'), ('python_training', 'Python Training'), ('excel_training', 'Excel Training'), ('computer_basics', 'Computer Basics'), ('powerbi_training', 'Power BI Training'), ('tableau_training', 'Tableau Training'), ('concept_note', 'Concept Note'), ('data_collection', 'Data Collection'), ('data_analysis', 'Data Analysis'), ('3d_rendering', '3D Rendering'), ('graphic_design', 'Graphic Design'), ('web_development', 'Web Development'), ('cv_creation', 'CV Creation')], max_length=50)),
                ('description', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_servic_status_0e4e59_idx'), models.Index(fields=['service', '-created_at'], name='core_servic_service_d5f8e5_idx')],
            },
        ),
    ]
