# Generated by Django 5.2.10 on 2026-03-16 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_submitted_by_to_servicerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCoursePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_mark_complete', models.BooleanField(default=False, help_text='Allow this instructor to mark courses as complete')),
                ('enabled_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='course_completion_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Course Permission',
                'verbose_name_plural': 'Instructor Course Permissions',
            },
        ),
    ]
