# Generated by Django 5.2.10 on 2026-03-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_instructor_course_permission'),
        ('courses', '0016_enrollment_completion_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable certificate generation for this course when student completes and instructor marks complete')),
                ('auto_generate', models.BooleanField(default=False, help_text='Automatically generate certificates when completion percentage reaches 100%')),
                ('require_perfect_score', models.BooleanField(default=False, help_text='Require 100% score on all quizzes to qualify for certificate')),
                ('require_full_attendance', models.BooleanField(default=False, help_text='Require 100% attendance to qualify for certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(help_text='Course for which certificates are configured', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_settings', to='courses.course')),
            ],
            options={
                'verbose_name': 'Certificate Settings',
                'verbose_name_plural': 'Certificate Settings',
            },
        ),
    ]
