# Generated by Django 5.2.10 on 2026-03-14 19:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0015_enrollment_coupon_enrollment_discount_applied_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_per_successful_referral', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Discount percentage or credit amount', max_digits=5)),
                ('reward_type', models.CharField(choices=[('DISCOUNT_CODE', 'Discount Code (Coupon)'), ('CREDIT', 'Account Credit')], default='DISCOUNT_CODE', max_length=20)),
                ('min_course_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum course price to qualify for referral bonus', max_digits=10)),
                ('reward_validity_days', models.IntegerField(default=90, help_text='Days the reward is valid')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable referral system')),
                ('max_rewards_per_student', models.IntegerField(default=0, help_text='Maximum rewards a student can earn (0 = unlimited)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Settings',
                'verbose_name_plural': 'Referral Settings',
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique referral code', max_length=20, unique=True)),
                ('referral_url', models.URLField(help_text='Full referral URL to share')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_referrals', models.IntegerField(default=0, help_text='Total number of sign-ups via this link')),
                ('successful_referrals', models.IntegerField(default=0, help_text='Referrals that resulted in paid enrollment')),
                ('total_rewards_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total credits/discounts earned', max_digits=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Link',
                'verbose_name_plural': 'Referral Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (User registered)'), ('ENROLLED', 'Enrolled in course'), ('PAID', 'Payment completed'), ('REWARD_PENDING', 'Reward pending approval'), ('REWARD_CLAIMED', 'Reward claimed')], default='PENDING', max_length=20)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
                ('enrollment_date', models.DateTimeField(blank=True, help_text='Date of first enrollment', null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date when payment was received', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this referral')),
                ('first_enrollment', models.ForeignKey(blank=True, help_text='First course enrollment by referred user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_source', to='courses.enrollment')),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referral_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referrallink')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-signup_date'],
                'unique_together': {('referral_link', 'referred_user')},
            },
        ),
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('DISCOUNT_CODE', 'Discount Code (Coupon)'), ('CREDIT', 'Account Credit')], default='DISCOUNT_CODE', max_length=20)),
                ('reward_value', models.DecimalField(decimal_places=2, help_text='Discount percentage or credit amount in currency', max_digits=10)),
                ('reward_description', models.CharField(help_text="e.g., '10% off', '$25 credit'", max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available to claim'), ('CLAIMED', 'Already claimed'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, help_text='When the reward was claimed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the reward expires')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_rewards', to='courses.coupon')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward', to='referrals.referral')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Reward',
                'verbose_name_plural': 'Referral Rewards',
                'ordering': ['-created_at'],
            },
        ),
    ]
