# Generated by Django 5.2.10 on 2026-03-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralreward',
            name='reward_type',
            field=models.CharField(choices=[('DISCOUNT_PERCENTAGE', 'Discount Percentage'), ('CREDIT_AMOUNT', 'Credit Amount')], default='DISCOUNT_PERCENTAGE', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='reward_type',
            field=models.CharField(choices=[('DISCOUNT_PERCENTAGE', 'Discount Percentage'), ('CREDIT_AMOUNT', 'Credit Amount')], default='DISCOUNT_PERCENTAGE', max_length=20),
        ),
    ]
