# Generated by Django 5.2.10 on 2026-03-15 06:59

from django.db import migrations


def migrate_reward_types(apps, schema_editor):
    """Migrate reward type values from old to new enum names."""
    ReferralReward = apps.get_model('referrals', 'ReferralReward')
    ReferralSettings = apps.get_model('referrals', 'ReferralSettings')
    
    # Update ReferralReward entries
    ReferralReward.objects.filter(reward_type='DISCOUNT_CODE').update(reward_type='DISCOUNT_PERCENTAGE')
    ReferralReward.objects.filter(reward_type='CREDIT').update(reward_type='CREDIT_AMOUNT')
    
    # Update ReferralSettings entries
    ReferralSettings.objects.filter(reward_type='DISCOUNT_CODE').update(reward_type='DISCOUNT_PERCENTAGE')
    ReferralSettings.objects.filter(reward_type='CREDIT').update(reward_type='CREDIT_AMOUNT')


def reverse_migrate_reward_types(apps, schema_editor):
    """Reverse the migration (for rollback)."""
    ReferralReward = apps.get_model('referrals', 'ReferralReward')
    ReferralSettings = apps.get_model('referrals', 'ReferralSettings')
    
    # Revert the changes
    ReferralReward.objects.filter(reward_type='DISCOUNT_PERCENTAGE').update(reward_type='DISCOUNT_CODE')
    ReferralReward.objects.filter(reward_type='CREDIT_AMOUNT').update(reward_type='CREDIT')
    
    ReferralSettings.objects.filter(reward_type='DISCOUNT_PERCENTAGE').update(reward_type='DISCOUNT_CODE')
    ReferralSettings.objects.filter(reward_type='CREDIT_AMOUNT').update(reward_type='CREDIT')


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_update_reward_type_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_reward_types, reverse_migrate_reward_types),
    ]
