# Generated by Django 5.2.10 on 2026-03-16 10:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_migrate_reward_type_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralreward',
            name='reward_description',
            field=models.CharField(help_text="e.g., '10% off', 'TZS 25,000 credit'", max_length=255),
        ),
        migrations.AlterField(
            model_name='referralsettings',
            name='reward_per_successful_referral',
            field=models.DecimalField(decimal_places=2, default=Decimal('10'), help_text='Discount percentage or credit amount', max_digits=10),
        ),
    ]
