# Generated by Django 5.2.10 on 2026-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_increase_reward_setting_max_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralreward',
            name='remaining_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining usable value after partial use (null = full value still available)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='reward_value',
            field=models.DecimalField(decimal_places=2, help_text='Original discount percentage or credit amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referralreward',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available to claim'), ('CLAIMED', 'Claimed — ready to use'), ('USED', 'Used in enrollment'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20),
        ),
    ]
