# Generated by Django 5.2.10 on 2026-01-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.TextField(default='Curriculum to be updated.', help_text='Detailed curriculum of the course'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='TBD', help_text="Expected training duration (e.g., '3 months')", max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('HYBRID', 'Hybrid (Online & Offline)')], default='ONLINE', help_text='Where the training will be done', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.PositiveIntegerField(default=0, help_text='Total hours the course will take'),
        ),
    ]
