# Generated by Django 5.2.10 on 2026-01-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='lipa_namba',
        ),
    ]
