# Generated by Django 5.2.10 on 2026-01-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_paymentmethod_lipa_namba'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='download_allowed',
            field=models.BooleanField(default=False, help_text='Allow students to download this resource'),
        ),
    ]
