# Generated by Django 5.2.10 on 2026-01-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_resource_download_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='payment_deadline',
            field=models.DateField(blank=True, help_text='Deadline for students to submit payment. Leave blank for no deadline.', null=True),
        ),
    ]
