# Generated by Django 5.2.10 on 2026-01-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_payment_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='certificate_generated',
            field=models.BooleanField(default=False, help_text='Track if certificate was generated'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False, help_text='Mark as True when student completes the course'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date and time when course was completed', null=True),
        ),
    ]
