# Generated by Django 5.2.10 on 2026-01-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_enrollment_certificate_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='When the course starts (used in certificates)', null=True),
        ),
    ]
