# Generated by Django 5.2.10 on 2026-03-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_module_lesson_lessoncompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Optional downloadable attachment for this lesson', max_length=500, null=True, upload_to='lessons/resources/%Y/%m/'),
        ),
    ]
