# Generated by Django 5.2.10 on 2026-03-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_lesson_progress_resource_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Session title (e.g., 'Week 1 Introduction')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session details and agenda')),
                ('meeting_link', models.URLField(help_text='Meeting URL (Zoom, Google Meet, Jitsi, or any URL)')),
                ('scheduled_at', models.DateTimeField(help_text='Date and time when the session will be held')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
