# Generated by Django 5.2.10 on 2026-03-14 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_livesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (e.g., SAVE20, SPRING2024)', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text="Description of the coupon (e.g., 'Spring Sale - 20% Off')", max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='percentage', help_text='Type of discount', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount (percentage 0-100 or fixed amount in TZS)', max_digits=10)),
                ('valid_from', models.DateTimeField(blank=True, help_text='When the coupon becomes valid', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the coupon expires', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (blank = unlimited)', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, help_text='Current number of times this coupon has been used')),
                ('is_active', models.BooleanField(default=True, help_text='Disable to deactivate the coupon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, help_text='Leave blank to apply to all courses', related_name='coupons', to='courses.course')),
                ('created_by', models.ForeignKey(help_text='Instructor or admin who created this coupon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
