# Generated by Django 5.2.10 on 2026-03-14 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='courses.coupon'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied (currency)', max_digits=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price after discount', max_digits=10, null=True),
        ),
    ]
