# Generated by Django 5.2.10 on 2026-03-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_enrollment_coupon_enrollment_discount_applied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completion_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Calculated completion percentage (0-100) from assignments, attendance, quizzes, and lessons'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instructor_marked_completed',
            field=models.BooleanField(default=False, help_text='Instructor has marked this course as completed (requires admin permission)'),
        ),
    ]
