# Generated by Django 5.2.10 on 2026-03-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_enrollment_completion_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_downloads', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_resource_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Resource Download',
                'verbose_name_plural': 'Lesson Resource Downloads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
