# Generated by Django 5.2.10 on 2026-03-14 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('assignment_new', 'New Assignment Posted'), ('assignment_graded', 'Assignment Graded'), ('assignment_reviewed', 'Assignment Reviewed'), ('assignment_resubmit', 'Needs Resubmission'), ('assignment_submitted', 'Assignment Submitted'), ('service_new', 'New Service Request'), ('service_status', 'Service Request Update'), ('payment_approved', 'Enrollment Approved'), ('course_enrolled', 'New Student Enrolled'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
