# Generated by Django 5.2.10 on 2026-03-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('assignment_new', 'New Assignment Posted'), ('assignment_graded', 'Assignment Graded'), ('assignment_reviewed', 'Assignment Reviewed'), ('assignment_resubmit', 'Needs Resubmission'), ('assignment_submitted', 'Assignment Submitted'), ('lesson_new', 'New Lesson Available'), ('module_new', 'New Module Added'), ('lesson_complete', 'Lesson Completed'), ('service_new', 'New Service Request'), ('service_status', 'Service Request Update'), ('payment_approved', 'Enrollment Approved'), ('course_enrolled', 'New Student Enrolled'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
